M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu24.04.1} date 2025-03-28T20:08:04+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-28T20:08:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.524
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X91.0Y-71.4
T2
X147.615Y-68.77
X147.615Y-89.09
T3
X90.5Y-66.0
X90.5Y-92.5
X153.5Y-66.0
X153.5Y-92.5
M30
